# Generated by Django 5.0.6 on 2024-07-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'active'), ('In-Active', 'inactive')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='urlshortapp.basemodel')),
                ('original_url', models.CharField(max_length=2000, verbose_name='small url')),
                ('redirect_url', models.CharField(max_length=5000, verbose_name='long url')),
            ],
            bases=('urlshortapp.basemodel',),
        ),
    ]
